Add get_documentation() to EnumMessage.
Peternator7/strum pull request #206
Opened 2022-01-10 09:57 UTC by orenbenkiki

Implement #203.

2022-01-15 21:05 UTC, Peternator7 commented
Thanks for the PR. Just a couple of minor tweaks I think.

I'm a little worried that people will mis-use this feature, and negatively impact the quaility of their own documentation, but I also see the practical benefit of something like this so I think it's okay.

2022-02-03 17:56 UTC, orenbenkiki commented
What are the minor tweaks you'd like to see?

2022-02-05 23:31 UTC, Peternator7 requested changes

2022-02-05 23:31 UTC, Peternator7 commented
I forgot to hit submit review :( sorry about that

2022-02-06 11:07 UTC, orenbenkiki commented on strum_macros/src/helpers/metadata.rs
> +        self.attrs.iter().filter(|attr| attr.path.is_ident("doc")).try_fold(result, |mut vec, attr| {
Done.

2022-02-06 11:17 UTC, orenbenkiki commented on strum_macros/src/macros/enum_messages.rs
> +                .push(quote! { &#name::#ident #params => ::core::option::Option::Some(concat!(#( #documentation ),*).trim()) });
To make this friendlier to markup, I remove the leading space from each line, and only if there are multiple lines, I suffix each one with a new line when I concatenate them. This way a single-line comment becomes a simple string (w/o a final newline) but a multi-line comment preserves the indentation structure and the final newline in each line.

2022-02-06 11:51 UTC, orenbenkiki commented on strum_tests/tests/enum_message.rs
> +    // I'm a silent dog.
Done.

2022-02-06 11:51 UTC, orenbenkiki commented on strum_tests/tests/enum_message.rs
> +    /// I'm disabled.
Done.

2022-02-06 11:53 UTC, orenbenkiki commented on strum_macros/Cargo.toml
> +strum = { path = "../strum" }
This is consistent with the way that `strum_tests` refers to the parent crate - I took it from there. So the answer should be "yes" for tests and I _assume_ also for docs? Is there a way to test this?

2022-02-06 11:55 UTC, orenbenkiki commented
Did a pass (trying) to address the review issues.

2022-02-07 07:47 UTC, orenbenkiki commented
Ok, checks pass now.

2022-02-12 20:25 UTC, Peternator7 commented on strum_macros/Cargo.toml
> +strum = { path = "../strum" }
I think it should be fine. My concern was that strum_tests isn't published to crates.io so it's behavior might not be correct for a published library. However, [this page](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies) suggests that it doesn't make a big difference

2022-02-21 21:35 UTC, Peternator7 approved these changes

2022-02-21 21:37 UTC, merged

2022-02-21 22:21 UTC, Peternator7 commented
Released as part of `0.24`